export const mainpageSideBar = {
    sidebarName: "DocsSidebar",
    sidebarItems: [
      {
        type: "category",
        label: "Authentication",
        items: [
          {
            type: "link",
            label: "Overview",
            href: "/docs/authentication/overview",
            docId: "authentication/overview",
            unlisted: false,
          },
          {
            type: "category",
            label: "Quick Start",
            items: [
              {
                type: "link",
                label: "Standard Login",
                href: "/docs/authentication/quick-start/standard-login",
                docId: "authentication/quick-start/standard-login",
                unlisted: false,
              },
              {
                type: "link",
                label: "Social Login",
                href: "/docs/authentication/quick-start/social-login",
                docId: "authentication/quick-start/social-login",
                unlisted: false,
              },
              {
                type: "link",
                label: "Single Sign-On",
                href: "/docs/authentication/quick-start/sso-implementation",
                docId: "authentication/quick-start/sso-implementation",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Tutorial",
            items: [
              {
                type: "link",
                label: "Phone Login",
                href: "/docs/authentication/tutorial/phone-login",
                docId: "authentication/tutorial/phone-login",
                unlisted: false,
              },
              {
                type: "link",
                label: "One Touch Login",
                href: "/docs/authentication/tutorial/one-touch-login",
                docId: "authentication/tutorial/one-touch-login",
                unlisted: false,
              },
              {
                type: "link",
                label: "Passkey Authentication",
                href: "/docs/authentication/tutorial/passkey-authentication",
                docId: "authentication/tutorial/passkey-authentication",
                unlisted: false,
              },
              {
                type: "link",
                label: "Passwordless Login",
                href: "/docs/authentication/tutorial/passwordless-login",
                docId: "authentication/tutorial/passwordless-login",
                unlisted: false,
              },
              {
                type: "link",
                label: "Smart Login",
                href: "/docs/authentication/tutorial/smart-login",
                docId: "authentication/tutorial/smart-login",
                unlisted: false,
              },
              {
                type: "link",
                label: "Username Login",
                href: "/docs/authentication/tutorial/username-login",
                docId: "authentication/tutorial/username-login",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Concepts",
            items: [
              {
                type: "link",
                label: "Password Policy",
                href: "/docs/authentication/concepts/password-policy",
                docId: "authentication/concepts/password-policy",
                unlisted: false,
              },
              {
                type: "link",
                label: "Email Communication and Configuration",
                href: "/docs/authentication/concepts/email-communications",
                docId: "authentication/concepts/email-communications",
                unlisted: false,
              },
              {
                type: "link",
                label: "Roles, Permissions and Context",
                href: "/docs/authentication/concepts/roles-and-membership",
                docId: "authentication/concepts/roles-and-membership",
                unlisted: false,
              },
              {
                type: "link",
                label: "Email Verifications Workflow",
                href: "/docs/authentication/concepts/email-verification-workflow",
                docId: "authentication/concepts/email-verification-workflow",
                unlisted: false,
              },
              {
                type: "link",
                label: "Advanced Workflow",
                href: "/docs/authentication/concepts/advanced-workflow",
                docId: "authentication/concepts/advanced-workflow",
                unlisted: false,
              },
              {
                type: "link",
                label: "Session Management and Configuration",
                href: "/docs/authentication/concepts/session-management",
                docId: "authentication/concepts/session-management",
                unlisted: false,
              },
              {
                type: "link",
                label: "SMS/Text/Voice OTP Provider",
                href: "/docs/authentication/concepts/sms-communication",
                docId: "authentication/concepts/sms-communication",
                unlisted: false,
              },
              {
                type: "link",
                label: "Customer Security",
                href: "/docs/authentication/concepts/customer-security",
                docId: "authentication/concepts/customer-security",
                unlisted: false,
              },
              {
                type: "link",
                label: "Progressive Profiling",
                href: "/docs/authentication/concepts/progressive-profiling",
                docId: "authentication/concepts/progressive-profiling",
                unlisted: false,
              },
              {
                type: "category",
                label: "Customer Data Management",
                items: [
                  {
                    type: "link",
                    label: "Customer Data Management",
                    href: "/docs/authentication/concepts/Customer Data Management/introduction",
                    docId:
                      "authentication/concepts/Customer Data Management/introduction",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "Customer Profile Editor",
                    href: "/docs/authentication/concepts/Customer Data Management/profile-editor",
                    docId:
                      "authentication/concepts/Customer Data Management/profile-editor",
                    unlisted: false,
                  },
                ],
                collapsed: true,
                collapsible: true,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "FAQ",
            items: [
              {
                type: "link",
                label: "Troubleshooting",
                href: "/docs/authentication/faq/troubleshooting",
                docId: "authentication/faq/troubleshooting",
                unlisted: false,
              },
              {
                type: "link",
                label: "Account Linking",
                href: "/docs/authentication/faq/account-linking",
                docId: "authentication/faq/account-linking",
                unlisted: false,
              },
              {
                type: "link",
                label: "Age Verification",
                href: "/docs/authentication/faq/age-verification",
                docId: "authentication/faq/age-verification",
                unlisted: false,
              },
              {
                type: "link",
                label: "Billing FAQ",
                href: "/docs/authentication/faq/billing-faq",
                docId: "authentication/faq/billing-faq",
                unlisted: false,
              },
              {
                type: "link",
                label: "Identity Provider Apps",
                href: "/docs/authentication/faq/identity-provider-apps",
                docId: "authentication/faq/identity-provider-apps",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Support",
                href: "/docs/authentication/faq/support-faq",
                docId: "authentication/faq/support-faq",
                unlisted: false,
              },
              {
                type: "link",
                label: "Supported Browsers",
                href: "/docs/authentication/faq/supported-browsers",
                docId: "authentication/faq/supported-browsers",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
        ],
        collapsed: true,
        collapsible: true,
      },
      {
        type: "category",
        label: "Customer Intelligence",
        items: [
          {
            type: "link",
            label: "Customer Intelligence",
            href: "/docs/customer-intelligence/overview",
            docId: "customer-intelligence/overview",
            unlisted: false,
          },
          {
            type: "link",
            label: "Analytics",
            href: "/docs/customer-intelligence/analytics-overview",
            docId: "customer-intelligence/analytics-overview",
            unlisted: false,
          },
          {
            type: "link",
            label: "Key Terminology",
            href: "/docs/customer-intelligence/key-terminology",
            docId: "customer-intelligence/key-terminology",
            unlisted: false,
          },
          {
            type: "link",
            label: "Identity Analytics",
            href: "/docs/customer-intelligence/identity-analytics",
            docId: "customer-intelligence/identity-analytics",
            unlisted: false,
          },
          {
            type: "link",
            label: "Provider Analytics",
            href: "/docs/customer-intelligence/provider-analytics",
            docId: "customer-intelligence/provider-analytics",
            unlisted: false,
          },
          {
            type: "link",
            label: "Login Analytics",
            href: "/docs/customer-intelligence/login-analytics",
            docId: "customer-intelligence/login-analytics",
            unlisted: false,
          },
          {
            type: "link",
            label: "Comparative Analytics",
            href: "/docs/customer-intelligence/comparative-analysis",
            docId: "customer-intelligence/comparative-analysis",
            unlisted: false,
          },
          {
            type: "link",
            label: "Utilizing Data Collected with LoginRadius",
            href: "/docs/customer-intelligence/utilize-insights-data",
            docId: "customer-intelligence/utilize-insights-data",
            unlisted: false,
          },
          {
            type: "link",
            label: "API Analytics",
            href: "/docs/customer-intelligence/api-analytics",
            docId: "customer-intelligence/api-analytics",
            unlisted: false,
          },
          {
            type: "link",
            label: "Communication Analytics",
            href: "/docs/customer-intelligence/sms-analytics",
            docId: "customer-intelligence/sms-analytics",
            unlisted: false,
          },
        ],
        collapsed: true,
        collapsible: true,
      },
      {
        type: "category",
        label: "Customer Management",
        items: [
          {
            type: "link",
            label: "Customer Management",
            href: "/docs/user-management/user-management/overview",
            docId: "user-management/user-management/overview",
            unlisted: false,
          },
          {
            type: "link",
            label: "Add a New Customer",
            href: "/docs/customer-management/add-a-new-customer",
            docId: "customer-management/add-a-new-customer",
            unlisted: false,
          },
          {
            type: "link",
            label: "View and Manage Customers",
            href: "/docs/customer-management/profile-view",
            docId: "customer-management/profile-view",
            unlisted: false,
          },
          {
            type: "link",
            label: "Blocked Customers",
            href: "/docs/customer-management/blocked-customer",
            docId: "customer-management/blocked-customer",
            unlisted: false,
          },
          {
            type: "category",
            label: "Customer Segmentation",
            items: [
              {
                type: "link",
                label: "Customer Segmentation",
                href: "/docs/customer-management/customer-segmentation/",
                docId:
                  "customer-management/customer-segmentation/customer-segmentation",
                unlisted: false,
              },
              {
                type: "link",
                label: "Basic Segmentation",
                href: "/docs/customer-management/customer-segmentation/basic-segmentation",
                docId:
                  "customer-management/customer-segmentation/basic-segmentation",
                unlisted: false,
              },
              {
                type: "link",
                label: "Advanced Segmentation",
                href: "/docs/customer-management/customer-segmentation/advanced-segmentation",
                docId:
                  "customer-management/customer-segmentation/advanced-segmentation",
                unlisted: false,
              },
              {
                type: "link",
                label: "Save Segmentation",
                href: "/docs/customer-management/customer-segmentation/save-segmentation",
                docId:
                  "customer-management/customer-segmentation/save-segmentation",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Data Query",
            items: [
              {
                type: "link",
                label: "Data Query",
                href: "/docs/customer-management/data-query/data-query-overview",
                docId: "customer-management/data-query/data-query-overview",
                unlisted: false,
              },
              {
                type: "link",
                label: "Customer Query",
                href: "/docs/customer-management/data-query/customer-query",
                docId: "customer-management/data-query/customer-query",
                unlisted: false,
              },
              {
                type: "link",
                label: "Custom Object Query",
                href: "/docs/customer-management/data-query/custom-object-query",
                docId: "customer-management/data-query/custom-object-query",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "User Data Export",
            items: [
              {
                type: "link",
                label: "User Data Export",
                href: "/docs/customer-management/user-data-export/data-export-overview",
                docId:
                  "customer-management/user-data-export/data-export-overview",
                unlisted: false,
              },
              {
                type: "link",
                label: "On-Demand Export",
                href: "/docs/customer-management/user-data-export/on-demand-export",
                docId: "customer-management/user-data-export/on-demand-export",
                unlisted: false,
              },
              {
                type: "link",
                label: "Scheduled Export",
                href: "/docs/customer-management/user-data-export/scheduled-export",
                docId: "customer-management/user-data-export/scheduled-export",
                unlisted: false,
              },
              {
                type: "link",
                label: "Export Logs",
                href: "/docs/customer-management/user-data-export/export-logs",
                docId: "customer-management/user-data-export/export-logs",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
        ],
        collapsed: true,
        collapsible: true,
      },
      {
        type: "category",
        label: "Governance",
        items: [
          {
            type: "link",
            label: "Overview",
            href: "/docs/governance/overview",
            docId: "governance/overview",
            unlisted: false,
          },
          {
            type: "link",
            label: "Standard Login Form Fields",
            href: "/docs/governance/data-schema",
            docId: "governance/data-schema",
            unlisted: false,
          },
          {
            type: "link",
            label: "Custom Field Configuration",
            href: "/docs/governance/custom-field-configuration",
            docId: "governance/custom-field-configuration",
            unlisted: false,
          },
          {
            type: "link",
            label: "Configure social data settings",
            href: "/docs/governance/configure-social-data-settings",
            docId: "governance/configure-social-data-settings",
            unlisted: false,
          },
          {
            type: "link",
            label: "Advanced Data-points Requirements and Retrieval",
            href: "/docs/governance/advanced-social-data-points",
            docId: "governance/advanced-social-data-points",
            unlisted: false,
          },
          {
            type: "category",
            label: "Customer Profiling",
            items: [
              {
                type: "link",
                label: "Customer Data Storage",
                href: "/docs/governance/customer-profiling/custom-fields-and-custom-objects",
                docId:
                  "governance/customer-profiling/custom-fields-and-custom-objects",
                unlisted: false,
              },
              {
                type: "link",
                label: "Custom Object",
                href: "/docs/governance/customer-profiling/custom-object-overview",
                docId: "governance/customer-profiling/custom-object-overview",
                unlisted: false,
              },
              {
                type: "link",
                label: "Customer Profile Scopes",
                href: "/docs/governance/customer-profiling/user-profile-scopes",
                docId: "governance/customer-profiling/user-profile-scopes",
                unlisted: false,
              },
              {
                type: "link",
                label: "Consent Management",
                href: "/docs/governance/customer-profiling/consent-management",
                docId: "governance/customer-profiling/consent-management",
                unlisted: false,
              },
              {
                type: "link",
                label: "Privacy Policy Versioning",
                href: "/docs/governance/customer-profiling/privacy-policy",
                docId: "governance/customer-profiling/privacy-policy",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Data Security",
                href: "/docs/governance/customer-profiling/data-security",
                docId: "governance/customer-profiling/data-security",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
        ],
        collapsed: true,
        collapsible: true,
      },
      {
        type: "category",
        label: "Integrations",
        items: [
          {
            type: "link",
            label: "Integrations",
            href: "/docs/integrations/overview",
            docId: "integrations/overview",
            unlisted: false,
          },
          {
            type: "link",
            label: "Available Integrations",
            href: "/docs/integrations/available-integrations",
            docId: "integrations/available-integrations",
            unlisted: false,
          },
          {
            type: "category",
            label: "Audit Log Integration",
            items: [
              {
                type: "link",
                label: "Overview",
                href: "/docs/integrations/audit-log/overview",
                docId: "integrations/audit-log/overview",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Cloud Connectors",
            items: [
              {
                type: "link",
                label: "Cloud Connectors",
                href: "/docs/integrations/server-side-cloud-connectors/overview",
                docId: "integrations/server-side-cloud-connectors/overview",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Client Side Connectors",
            items: [
              {
                type: "link",
                label: "Client-Side Integration",
                href: "/docs/integrations/client-side-connectors/getting-started",
                docId: "integrations/client-side-connectors/getting-started",
                unlisted: false,
              },
              {
                type: "link",
                label: "Amplitude",
                href: "/docs/integrations/client-side-connectors/amplitude",
                docId: "integrations/client-side-connectors/amplitude",
                unlisted: false,
              },
              {
                type: "link",
                label: "Customer.io",
                href: "/docs/integrations/client-side-connectors/customerio",
                docId: "integrations/client-side-connectors/customerio",
                unlisted: false,
              },
              {
                type: "link",
                label: "Facebook App Events",
                href: "/docs/integrations/client-side-connectors/facebook-app-events",
                docId: "integrations/client-side-connectors/facebook-app-events",
                unlisted: false,
              },
              {
                type: "link",
                label: "Google Analytics",
                href: "/docs/integrations/client-side-connectors/google-analytics",
                docId: "integrations/client-side-connectors/google-analytics",
                unlisted: false,
              },
              {
                type: "link",
                label: "Google DoubleClick For Publishers (DFP)",
                href: "/docs/integrations/client-side-connectors/google-dfp",
                docId: "integrations/client-side-connectors/google-dfp",
                unlisted: false,
              },
              {
                type: "link",
                label: "GoSquared",
                href: "/docs/integrations/client-side-connectors/gosquared",
                docId: "integrations/client-side-connectors/gosquared",
                unlisted: false,
              },
              {
                type: "link",
                label: "Hubspot",
                href: "/docs/integrations/client-side-connectors/hubspot",
                docId: "integrations/client-side-connectors/hubspot",
                unlisted: false,
              },
              {
                type: "link",
                label: "Intercom",
                href: "/docs/integrations/client-side-connectors/intercom",
                docId: "integrations/client-side-connectors/intercom",
                unlisted: false,
              },
              {
                type: "link",
                label: "Keen",
                href: "/docs/integrations/client-side-connectors/keen",
                docId: "integrations/client-side-connectors/keen",
                unlisted: false,
              },
              {
                type: "link",
                label: "Kissmetrics",
                href: "/docs/integrations/client-side-connectors/kissmetrics",
                docId: "integrations/client-side-connectors/kissmetrics",
                unlisted: false,
              },
              {
                type: "link",
                label: "Lotame",
                href: "/docs/integrations/client-side-connectors/lotame",
                docId: "integrations/client-side-connectors/lotame",
                unlisted: false,
              },
              {
                type: "link",
                label: "Matomo",
                href: "/docs/integrations/client-side-connectors/matomo",
                docId: "integrations/client-side-connectors/matomo",
                unlisted: false,
              },
              {
                type: "link",
                label: "Mixpanel",
                href: "/docs/integrations/client-side-connectors/mixpanel",
                docId: "integrations/client-side-connectors/mixpanel",
                unlisted: false,
              },
              {
                type: "link",
                label: "Olark",
                href: "/docs/integrations/client-side-connectors/olark",
                docId: "integrations/client-side-connectors/olark",
                unlisted: false,
              },
              {
                type: "link",
                label: "Salesmachine",
                href: "/docs/integrations/client-side-connectors/salesmachine",
                docId: "integrations/client-side-connectors/salesmachine",
                unlisted: false,
              },
              {
                type: "link",
                label: "Wootric",
                href: "/docs/integrations/client-side-connectors/wootric",
                docId: "integrations/client-side-connectors/wootric",
                unlisted: false,
              },
              {
                type: "link",
                label: "Zendesk",
                href: "/docs/integrations/client-side-connectors/zendesk",
                docId: "integrations/client-side-connectors/zendesk",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Third Party Integration Platforms",
            items: [
              {
                type: "link",
                label: "3rd Party Integration Platforms",
                href: "/docs/integrations/third-party-integration-platforms/overview",
                docId: "integrations/third-party-integration-platforms/overview",
                unlisted: false,
              },
              {
                type: "link",
                label: "Segment",
                href: "/docs/integrations/third-party-integration-platforms/segment",
                docId: "integrations/third-party-integration-platforms/segment",
                unlisted: false,
              },
              {
                type: "link",
                label: "Zapier Integration",
                href: "/docs/integrations/third-party-integration-platforms/zapier",
                docId: "integrations/third-party-integration-platforms/zapier",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Internet of Things (IoT)",
            items: [
              {
                type: "link",
                label: "Alexa Skills Kit Integration",
                href: "/docs/integrations/internet-of-things-iot/alexa-skills-kit",
                docId: "integrations/internet-of-things-iot/alexa-skills-kit",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Google Assistant Integration",
                href: "/docs/integrations/internet-of-things-iot/google-assistant",
                docId: "integrations/internet-of-things-iot/google-assistant",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Marketplace",
            items: [
              {
                type: "link",
                label: "Microsoft Dynamics",
                href: "/docs/integrations/marketplace/microsoft-dynamics",
                docId: "integrations/marketplace/microsoft-dynamics",
                unlisted: false,
              },
              {
                type: "link",
                label: "Disqus",
                href: "/docs/integrations/marketplace/disqus",
                docId: "integrations/marketplace/disqus",
                unlisted: false,
              },
              {
                type: "link",
                label: "Zendesk App Integration",
                href: "/docs/integrations/marketplace/zendesk-app",
                docId: "integrations/marketplace/zendesk-app",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
        ],
        collapsed: true,
        collapsible: true,
      },
      {
        type: "category",
        label: "Libraries",
        items: [
          {
            type: "link",
            label: "Deployment",
            href: "/docs/libraries/overview",
            docId: "libraries/overview",
            unlisted: false,
          },
          {
            type: "category",
            label: "JS Libraries",
            items: [
              {
                type: "link",
                label: "User Registration Getting Started",
                href: "/docs/libraries/js-libraries/getting-started",
                docId: "libraries/js-libraries/getting-started",
                unlisted: false,
              },
              {
                type: "link",
                label: "JavaScript Hooks",
                href: "/docs/libraries/js-libraries/javascript-hooks",
                docId: "libraries/js-libraries/javascript-hooks",
                unlisted: false,
              },
              {
                type: "link",
                label: "Advanced JS Customizations",
                href: "/docs/libraries/js-libraries/advanced-js-customizations",
                docId: "libraries/js-libraries/advanced-js-customizations",
                unlisted: false,
              },
              {
                type: "link",
                label: "JS Form Library",
                href: "/docs/libraries/js-libraries/js-form-library",
                docId: "libraries/js-libraries/js-form-library",
                unlisted: false,
              },
              {
                type: "link",
                label: "Localization",
                href: "/docs/libraries/js-libraries/localization",
                docId: "libraries/js-libraries/localization",
                unlisted: false,
              },
              {
                type: "link",
                label: "Customization based on device, location or browser",
                href: "/docs/libraries/js-libraries/customization-by-context",
                docId: "libraries/js-libraries/customization-by-context",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Identity Experience Framework",
            items: [
              {
                type: "link",
                label: "Overview",
                href: "/docs/libraries/identity-experience-framework/overview",
                docId: "libraries/identity-experience-framework/overview",
                unlisted: false,
              },
              {
                type: "link",
                label: "Usage",
                href: "/docs/libraries/identity-experience-framework/usage",
                docId: "libraries/identity-experience-framework/usage",
                unlisted: false,
              },
              {
                type: "link",
                label: "Customization",
                href: "/docs/libraries/identity-experience-framework/customization",
                docId: "libraries/identity-experience-framework/customization",
                unlisted: false,
              },
              {
                type: "link",
                label: "Features/Use Cases",
                href: "/docs/libraries/identity-experience-framework/features-use-cases",
                docId:
                  "libraries/identity-experience-framework/features-use-cases",
                unlisted: false,
              },
              {
                type: "link",
                label: "Multi-Branding Configuration",
                href: "/docs/libraries/identity-experience-framework/multi-branding-configuration",
                docId:
                  "libraries/identity-experience-framework/multi-branding-configuration",
                unlisted: false,
              },
              {
                type: "link",
                label: "Idx-selfhosted",
                href: "/docs/libraries/identity-experience-framework/idx-selfhosted",
                docId: "libraries/identity-experience-framework/idx-selfhosted",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "SDK Libraries",
            items: [
              {
                type: "link",
                label: "SDK Libraries",
                href: "/docs/libraries/sdk-libraries/overview",
                docId: "libraries/sdk-libraries/overview",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Mobile SDK Libraries",
            items: [
              {
                type: "link",
                label: "Mobile SDK",
                href: "/docs/libraries/mobile-sdk-libraries/overview",
                docId: "libraries/mobile-sdk-libraries/overview",
                unlisted: false,
              },
              {
                type: "link",
                label: "iOS Library",
                href: "/docs/libraries/mobile-sdk-libraries/ios-library",
                docId: "libraries/mobile-sdk-libraries/ios-library",
                unlisted: false,
              },
              {
                type: "link",
                label: "Android Library",
                href: "/docs/libraries/mobile-sdk-libraries/android-library",
                docId: "libraries/mobile-sdk-libraries/android-library",
                unlisted: false,
              },
              {
                type: "link",
                label: "Ionic Library",
                href: "/docs/libraries/mobile-sdk-libraries/ionic-library",
                docId: "libraries/mobile-sdk-libraries/ionic-library",
                unlisted: false,
              },
              {
                type: "link",
                label: "Ionic-2 Library",
                href: "/docs/libraries/mobile-sdk-libraries/ionic-2-library",
                docId: "libraries/mobile-sdk-libraries/ionic-2-library",
                unlisted: false,
              },
              {
                type: "link",
                label: "PhoneGap Library",
                href: "/docs/libraries/mobile-sdk-libraries/phonegap-library",
                docId: "libraries/mobile-sdk-libraries/phonegap-library",
                unlisted: false,
              },
              {
                type: "link",
                label: "Xamarin Library",
                href: "/docs/libraries/mobile-sdk-libraries/xamarin-library",
                docId: "libraries/mobile-sdk-libraries/xamarin-library",
                unlisted: false,
              },
              {
                type: "link",
                label: "React-Native Library",
                href: "/docs/libraries/mobile-sdk-libraries/react-native-library",
                docId: "libraries/mobile-sdk-libraries/react-native-library",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Turn-Key Plugins",
            items: [
              {
                type: "link",
                label: "TurnKey Plugins",
                href: "/docs/libraries/turn-key-plugins/overview",
                docId: "libraries/turn-key-plugins/overview",
                unlisted: false,
              },
              {
                type: "link",
                label: "General CMS Integrations",
                href: "/docs/libraries/turn-key-plugins/general-cms-integrations",
                docId: "libraries/turn-key-plugins/general-cms-integrations",
                unlisted: false,
              },
              {
                type: "link",
                label: "PerfectMind SSO Implementation",
                href: "/docs/libraries/turn-key-plugins/perfectmind",
                docId: "libraries/turn-key-plugins/perfectmind",
                unlisted: false,
              },
              {
                type: "link",
                label:
                  "Drupal v7.x Customer Identity and Access Management Module Instructions",
                href: "/docs/libraries/turn-key-plugins/drupal-v7-x-customer-identity-module-instructions",
                docId:
                  "libraries/turn-key-plugins/drupal-v7-x-customer-identity-module-instructions",
                unlisted: false,
              },
              {
                type: "link",
                label:
                  "Drupal v8.x and v9.x Customer Identity and Access Management Module Instruction",
                href: "/docs/libraries/turn-key-plugins/drupal-v8-x-customer-identity-module-instructions",
                docId:
                  "libraries/turn-key-plugins/drupal-v8-x-customer-identity-module-instructions",
                unlisted: false,
              },
              {
                type: "link",
                label:
                  "Joomla Customer Identity and Access Management Extension instructions for v2.x and v3.x",
                href: "/docs/libraries/turn-key-plugins/joomla-v2-x-and-v3-x-customer-identity-module-instructions",
                docId:
                  "libraries/turn-key-plugins/joomla-v2-x-and-v3-x-customer-identity-module-instructions",
                unlisted: false,
              },
              {
                type: "link",
                label:
                  "Magento Customer Identity and Access Management Extension instructions for v1.x",
                href: "/docs/libraries/turn-key-plugins/magento-1-x-extension",
                docId: "libraries/turn-key-plugins/magento-1-x-extension",
                unlisted: false,
              },
              {
                type: "link",
                label:
                  "Magento Customer Identity and Access Management Extension instructions for v2.x",
                href: "/docs/libraries/turn-key-plugins/magento-2-x-extension",
                docId: "libraries/turn-key-plugins/magento-2-x-extension",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Integration with Sitecore",
                href: "/docs/libraries/turn-key-plugins/sitecore-integration",
                docId: "libraries/turn-key-plugins/sitecore-integration",
                unlisted: false,
              },
              {
                type: "link",
                label: "Wordpress Customer Identity and Access Management Plugin",
                href: "/docs/libraries/turn-key-plugins/wordpress-2-x-plugin",
                docId: "libraries/turn-key-plugins/wordpress-2-x-plugin",
                unlisted: false,
              },
              {
                type: "link",
                label:
                  "BigCommerce Customer Identity and Access Management Plugin - BluePrint",
                href: "/docs/libraries/turn-key-plugins/bigcommerce-blueprint-plugin",
                docId: "libraries/turn-key-plugins/bigcommerce-blueprint-plugin",
                unlisted: false,
              },
              {
                type: "link",
                label:
                  "BigCommerce Customer Identity and Access Management Plugin - Stencil",
                href: "/docs/libraries/turn-key-plugins/bigcommerce-stencil-plugin",
                docId: "libraries/turn-key-plugins/bigcommerce-stencil-plugin",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Shopify Multipass Integration",
                href: "/docs/libraries/turn-key-plugins/shopify-multipass-integration",
                docId: "libraries/turn-key-plugins/shopify-multipass-integration",
                unlisted: false,
              },
              {
                type: "link",
                label: "Salesforce Commerce Cloud Cartridge",
                href: "/docs/libraries/turn-key-plugins/salesforce-commerce-cloud-cartridge",
                docId:
                  "libraries/turn-key-plugins/salesforce-commerce-cloud-cartridge",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Integration with AEM",
                href: "/docs/libraries/turn-key-plugins/aem-Integration",
                docId: "libraries/turn-key-plugins/aem-Integration",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Integration with SAP Hybris",
                href: "/docs/libraries/turn-key-plugins/hybris-Integration",
                docId: "libraries/turn-key-plugins/hybris-Integration",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Use Cases/Demos",
            items: [
              {
                type: "link",
                label: "Use Cases/Demos",
                href: "/docs/libraries/demos/overview",
                docId: "libraries/demos/overview",
                unlisted: false,
              },
              {
                type: "link",
                label: "HTML and JS Demo",
                href: "/docs/libraries/demos/html-and-js-demo",
                docId: "libraries/demos/html-and-js-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "HTML Themed Demo",
                href: "/docs/libraries/demos/html-themed-demo",
                docId: "libraries/demos/html-themed-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "Identity Experience Framework iframe Implementation",
                href: "/docs/libraries/demos/iframe-implementation-demo",
                docId: "libraries/demos/iframe-implementation-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "AMP Configuration",
                href: "/docs/libraries/demos/amp-demo",
                docId: "libraries/demos/amp-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius AngularJS Demo",
                href: "/docs/libraries/demos/angularjs-demo",
                docId: "libraries/demos/angularjs-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Angular 6 Demo",
                href: "/docs/libraries/demos/angular-6-demo",
                docId: "libraries/demos/angular-6-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius EmberJS Demo",
                href: "/docs/libraries/demos/emberjs-demo",
                docId: "libraries/demos/emberjs-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Google Assistant Demo",
                href: "/docs/libraries/demos/google-assistant-demo",
                docId: "libraries/demos/google-assistant-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Polymer Demo",
                href: "/docs/libraries/demos/polymer-demo",
                docId: "libraries/demos/polymer-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius React Demo",
                href: "/docs/libraries/demos/react-demo",
                docId: "libraries/demos/react-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Vue.js Demo",
                href: "/docs/libraries/demos/vue-demo",
                docId: "libraries/demos/vue-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Preact Demo",
                href: "/docs/libraries/demos/preact-demo",
                docId: "libraries/demos/preact-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Aurelia Demo",
                href: "/docs/libraries/demos/aurelia-demo",
                docId: "libraries/demos/aurelia-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Meteor Demo",
                href: "/docs/libraries/demos/meteor-demo",
                docId: "libraries/demos/meteor-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Backbone.JS Demo",
                href: "/docs/libraries/demos/backbonejs-demo",
                docId: "libraries/demos/backbonejs-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius CakePHP Demo",
                href: "/docs/libraries/demos/cakephp-demo",
                docId: "libraries/demos/cakephp-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius CodeIgniter Demo",
                href: "/docs/libraries/demos/codeigniter-demo",
                docId: "libraries/demos/codeigniter-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Laravel Demo",
                href: "/docs/libraries/demos/laravel-demo",
                docId: "libraries/demos/laravel-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Symfony Demo",
                href: "/docs/libraries/demos/symfony-demo",
                docId: "libraries/demos/symfony-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius YII Demo",
                href: "/docs/libraries/demos/yii-demo",
                docId: "libraries/demos/yii-demo",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Alexa Demo",
                href: "/docs/libraries/demos/alexa-demo",
                docId: "libraries/demos/alexa-demo",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Identity Orchestration",
            items: [
              {
                type: "link",
                label: "Identity Orchestration (IO)",
                href: "/docs/libraries/identity-orchestration/overview",
                docId: "libraries/identity-orchestration/overview",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Command Line Interface",
            items: [
              {
                type: "link",
                label: "Welcome to the LoginRadius CLI",
                href: "/docs/libraries/command-line-interface/cli",
                docId: "libraries/command-line-interface/cli",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
        ],
        collapsed: true,
        collapsible: true,
      },
      {
        type: "category",
        label: "Security",
        items: [
          {
            type: "link",
            label: "Security",
            href: "/docs/security/overview",
            docId: "security/overview",
            unlisted: false,
          },
          {
            type: "category",
            label: "Infrastructure",
            items: [
              {
                type: "link",
                label: "LoginRadius Global CDN",
                href: "/docs/security/infrastructure/loginradius-cdn",
                docId: "security/infrastructure/loginradius-cdn",
                unlisted: false,
              },
              {
                type: "link",
                label: "Overview",
                href: "/docs/security/infrastructure/multiple-environment",
                docId: "security/infrastructure/multiple-environment",
                unlisted: false,
              },
              {
                type: "link",
                label: "SMTP Overview",
                href: "/docs/security/infrastructure/smtp-overview",
                docId: "security/infrastructure/smtp-overview",
                unlisted: false,
              },
              {
                type: "link",
                label: "IP addresses of LoginRadius services",
                href: "/docs/security/infrastructure/ip-addresses-list",
                docId: "security/infrastructure/ip-addresses-list",
                unlisted: false,
              },
              {
                type: "link",
                label: "LoginRadius Data Regions",
                href: "/docs/security/infrastructure/loginradius-data-regions",
                docId: "security/infrastructure/loginradius-data-regions",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Platform Security",
            items: [
              {
                type: "link",
                label: "Account Verification",
                href: "/docs/security/platform-security/account-verification-overview",
                docId: "security/platform-security/account-verification-overview",
                unlisted: false,
              },
              {
                type: "link",
                label: "Threat Prevention On The LoginRadius Platform",
                href: "/docs/security/platform-security/threat-prevention",
                docId: "security/platform-security/threat-prevention",
                unlisted: false,
              },
              {
                type: "link",
                label: "Identity Data Compliance",
                href: "/docs/security/platform-security/identity-data-compliance",
                docId: "security/platform-security/identity-data-compliance",
                unlisted: false,
              },
              {
                type: "link",
                label: "Social Data Compliance",
                href: "/docs/security/platform-security/social-data-compliance",
                docId: "security/platform-security/social-data-compliance",
                unlisted: false,
              },
              {
                type: "link",
                label: "Password Security Concepts",
                href: "/docs/security/platform-security/password-security",
                docId: "security/platform-security/password-security",
                unlisted: false,
              },
              {
                type: "link",
                label: "Cryptographic Hashing Algorithms",
                href: "/docs/security/platform-security/cryptographic-hashing-algorithms",
                docId:
                  "security/platform-security/cryptographic-hashing-algorithms",
                unlisted: false,
              },
              {
                type: "link",
                label: "Data Migration Security and Sanitization",
                href: "/docs/security/platform-security/data-migration-security",
                docId: "security/platform-security/data-migration-security",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Data Management",
            items: [
              {
                type: "link",
                label: "Customer Data",
                href: "/docs/security/data-management/user-data-overview",
                docId: "security/data-management/user-data-overview",
                unlisted: false,
              },
              {
                type: "link",
                label:
                  "Confidentiality, Integrity, and Availability with LoginRadius",
                href: "/docs/security/data-management/confidentiality-integrity-and-availability",
                docId:
                  "security/data-management/confidentiality-integrity-and-availability",
                unlisted: false,
              },
              {
                type: "link",
                label: "About LoginRadius Tokens",
                href: "/docs/security/data-management/loginradius-tokens",
                docId: "security/data-management/loginradius-tokens",
                unlisted: false,
              },
              {
                type: "link",
                label: "Data Auditing and Logging",
                href: "/docs/security/data-management/data-auditing-andlogging",
                docId: "security/data-management/data-auditing-andlogging",
                unlisted: false,
              },
              {
                type: "link",
                label: "Consumer Audit Logs",
                href: "/docs/security/data-management/consumer-audit-logs",
                docId: "security/data-management/consumer-audit-logs",
                unlisted: false,
              },
              {
                type: "link",
                label: "Browser - Data Storage & Cookies",
                href: "/docs/security/data-management/browser-information-storage-cookies",
                docId:
                  "security/data-management/browser-information-storage-cookies",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Customer Security",
            items: [
              {
                type: "link",
                label: "Fraud Prevention On The LoginRadius Platform",
                href: "/docs/security/user-security/fraud-prevention",
                docId: "security/user-security/fraud-prevention",
                unlisted: false,
              },
              {
                type: "link",
                label: "Registration Security",
                href: "/docs/security/user-security/registration-security",
                docId: "security/user-security/registration-security",
                unlisted: false,
              },
              {
                type: "link",
                label: "Login Security",
                href: "/docs/security/user-security/login-security",
                docId: "security/user-security/login-security",
                unlisted: false,
              },
              {
                type: "link",
                label: "Password Management",
                href: "/docs/security/user-security/password-management",
                docId: "security/user-security/password-management",
                unlisted: false,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
        ],
        collapsed: true,
        collapsible: true,
      },
      {
        type: "category",
        label: "Single Sign-on",
        items: [
          {
            type: "link",
            label: "SSO",
            href: "/docs/single-sign-on/overview",
            docId: "single-sign-on/overview",
            unlisted: false,
          },
          {
            type: "category",
            label: "Tutorial",
            items: [
              {
                type: "link",
                label: "Web SSO",
                href: "/docs/single-sign-on/tutorial/web-sso/overview",
                docId: "single-sign-on/tutorial/web-sso/overview",
                unlisted: false,
              },
              {
                type: "link",
                label: "Mobile SSO",
                href: "/docs/single-sign-on/tutorial/mobile-sso/overview",
                docId: "single-sign-on/tutorial/mobile-sso/overview",
                unlisted: false,
              },
              {
                type: "category",
                label: "Federated SSO",
                items: [
                  {
                    type: "link",
                    label: "Pre-Built Connections",
                    href: "/docs/single-sign-on/tutorial/federated-sso/pre-built-connections",
                    docId:
                      "single-sign-on/tutorial/federated-sso/pre-built-connections",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "OAuth 2.0",
                    href: "/docs/single-sign-on/tutorial/federated-sso/oauth-2-0/oauth-2-0-overview",
                    docId:
                      "single-sign-on/tutorial/federated-sso/oauth-2-0/oauth-2-0-overview",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "OpenID Connect",
                    href: "/docs/single-sign-on/tutorial/federated-sso/openid-connect/openid-connect-overview",
                    docId:
                      "single-sign-on/tutorial/federated-sso/openid-connect/openid-connect-overview",
                    unlisted: false,
                  },
                  {
                    type: "category",
                    label: "JWT Login",
                    items: [
                      {
                        type: "link",
                        label: "JWT Login",
                        href: "/docs/single-sign-on/tutorial/federated-sso/jwt-login/jwt-login-overview",
                        docId:
                          "single-sign-on/tutorial/federated-sso/jwt-login/jwt-login-overview",
                        unlisted: false,
                      },
                      {
                        type: "link",
                        label: "Implementation of JWT",
                        href: "/docs/single-sign-on/tutorial/federated-sso/jwt-login/jwt-implementation-guide",
                        docId:
                          "single-sign-on/tutorial/federated-sso/jwt-login/jwt-implementation-guide",
                        unlisted: false,
                      },
                      {
                        type: "link",
                        label: "Generate JWT Algos",
                        href: "/docs/single-sign-on/tutorial/federated-sso/jwt-login/jwt-generate-algos",
                        docId:
                          "single-sign-on/tutorial/federated-sso/jwt-login/jwt-generate-algos",
                        unlisted: false,
                      },
                    ],
                    collapsed: true,
                    collapsible: true,
                  },
                  {
                    type: "category",
                    label: "SAML",
                    items: [
                      {
                        type: "link",
                        label: "Overview",
                        href: "/docs/single-sign-on/tutorial/federated-sso/saml/overview",
                        docId:
                          "single-sign-on/tutorial/federated-sso/saml/overview",
                        unlisted: false,
                      },
                      {
                        type: "link",
                        label: "Identity Provider Initiated SSO",
                        href: "/docs/single-sign-on/tutorial/federated-sso/saml/idp-initiated",
                        docId:
                          "single-sign-on/tutorial/federated-sso/saml/idp-initiated",
                        unlisted: false,
                      },
                      {
                        type: "link",
                        label: "Service Provider Initiated Login (SAML)",
                        href: "/docs/single-sign-on/tutorial/federated-sso/saml/sp-initiated",
                        docId:
                          "single-sign-on/tutorial/federated-sso/saml/sp-initiated",
                        unlisted: false,
                      },
                    ],
                    collapsed: true,
                    collapsible: true,
                  },
                ],
                collapsed: true,
                collapsible: true,
              },
              {
                type: "category",
                label: "Cross Device SSO",
                items: [
                  {
                    type: "link",
                    label: "Cross-Device SSO",
                    href: "/docs/single-sign-on/tutorial/cross-device-sso/overview",
                    docId: "single-sign-on/tutorial/cross-device-sso/overview",
                    unlisted: false,
                  },
                ],
                collapsed: true,
                collapsible: true,
              },
              {
                type: "category",
                label: "Custom IDPs",
                items: [
                  {
                    type: "link",
                    label: "Overview",
                    href: "/docs/single-sign-on/tutorial/custom-identity-providers/overview",
                    docId:
                      "single-sign-on/tutorial/custom-identity-providers/overview",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "Pre-Built Connections",
                    href: "/docs/single-sign-on/tutorial/custom-identity-providers/pre-built-connections",
                    docId:
                      "single-sign-on/tutorial/custom-identity-providers/pre-built-connections",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "Custom OAuth Provider",
                    href: "/docs/single-sign-on/tutorial/custom-identity-providers/custom-oauth-provider",
                    docId:
                      "single-sign-on/tutorial/custom-identity-providers/custom-oauth-provider",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "JWT as IDP",
                    href: "/docs/single-sign-on/tutorial/custom-identity-providers/custom-jwt-provider",
                    docId:
                      "single-sign-on/tutorial/custom-identity-providers/custom-jwt-provider",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "Custom SAML Provider",
                    href: "/docs/single-sign-on/tutorial/custom-identity-providers/custom-saml-provider",
                    docId:
                      "single-sign-on/tutorial/custom-identity-providers/custom-saml-provider",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "ADFS as Identity Provider",
                    href: "/docs/single-sign-on/tutorial/custom-identity-providers/custom-adfs-provider",
                    docId:
                      "single-sign-on/tutorial/custom-identity-providers/custom-adfs-provider",
                    unlisted: false,
                  },
                ],
                collapsed: true,
                collapsible: true,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
          {
            type: "category",
            label: "Concept",
            items: [
              {
                type: "category",
                label: "Custom IDP Providers",
                items: [
                  {
                    type: "link",
                    label: "Setup Azure AD as an Id Provider",
                    href: "/docs/single-sign-on/concept/custom-idp-provider/azure-ad",
                    docId: "single-sign-on/concept/custom-idp-provider/azure-ad",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "Doximity Integration",
                    href: "/docs/single-sign-on/concept/custom-idp-provider/doximity",
                    docId: "single-sign-on/concept/custom-idp-provider/doximity",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "AliPay",
                    href: "/docs/single-sign-on/concept/custom-idp-provider/alipay",
                    docId: "single-sign-on/concept/custom-idp-provider/alipay",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "AWS Cognito as Custom IDP With LoginRadius",
                    href: "/docs/single-sign-on/concept/custom-idp-provider/aws-cognito",
                    docId:
                      "single-sign-on/concept/custom-idp-provider/aws-cognito",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "Auth0 as custom IDP in LoginRadius",
                    href: "/docs/single-sign-on/concept/custom-idp-provider/autho",
                    docId: "single-sign-on/concept/custom-idp-provider/autho",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label:
                      "LoginRadius App as Custom IDP With Another LoginRadius App",
                    href: "/docs/single-sign-on/concept/custom-idp-provider/lr-as-custom-idp-into-another-lr-app",
                    docId:
                      "single-sign-on/concept/custom-idp-provider/lr-as-custom-idp-into-another-lr-app",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "wechat",
                    href: "/docs/single-sign-on/concept/custom-idp-provider/wechat",
                    docId: "single-sign-on/concept/custom-idp-provider/wechat",
                    unlisted: false,
                  },
                ],
                collapsed: true,
                collapsible: true,
              },
              {
                type: "category",
                label: "SAML Providers",
                items: [
                  {
                    type: "link",
                    label: "LoginRadius as IDP with Domo as SP",
                    href: "/docs/single-sign-on/concept/saml-providers/domo",
                    docId: "single-sign-on/concept/saml-providers/domo",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "LoginRadius as IDP with JIRA as SP",
                    href: "/docs/single-sign-on/concept/saml-providers/jira",
                    docId: "single-sign-on/concept/saml-providers/jira",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "LoginRadius as IDP with Salesforce as SP",
                    href: "/docs/single-sign-on/concept/saml-providers/salesforce",
                    docId: "single-sign-on/concept/saml-providers/salesforce",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "LoginRadius as IdP with Office 365 as SP",
                    href: "/docs/single-sign-on/concept/saml-providers/office365",
                    docId: "single-sign-on/concept/saml-providers/office365",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "LoginRadius as IdP with SharePoint as SP",
                    href: "/docs/single-sign-on/concept/saml-providers/sharepoint",
                    docId: "single-sign-on/concept/saml-providers/sharepoint",
                    unlisted: false,
                  },
                ],
                collapsed: true,
                collapsible: true,
              },
              {
                type: "category",
                label: "OIDC Providers",
                items: [
                  {
                    type: "link",
                    label:
                      "LoginRadius as IDP in Azure AD B2C using OIDC CONNECT",
                    href: "/docs/single-sign-on/concept/oidc-providers/azure-ad-b2c",
                    docId: "single-sign-on/concept/oidc-providers/azure-ad-b2c",
                    unlisted: false,
                  },
                ],
                collapsed: true,
                collapsible: true,
              },
              {
                type: "category",
                label: "SAML Miscellaneous",
                items: [
                  {
                    type: "link",
                    label: "SAML FAQ",
                    href: "/docs/single-sign-on/concept/saml-miscellaneous/samlfaq",
                    docId: "single-sign-on/concept/saml-miscellaneous/samlfaq",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "usage",
                    href: "/docs/single-sign-on/concept/saml-miscellaneous/usage",
                    docId: "single-sign-on/concept/saml-miscellaneous/usage",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "certificate",
                    href: "/docs/single-sign-on/concept/saml-miscellaneous/certificate",
                    docId:
                      "single-sign-on/concept/saml-miscellaneous/certificate",
                    unlisted: false,
                  },
                ],
                collapsed: true,
                collapsible: true,
              },
              {
                type: "category",
                label: "FAQ",
                items: [
                  {
                    type: "link",
                    label: "Chrome blocking third-party cookies",
                    href: "/docs/single-sign-on/faq/chrome-blocking-third-party-cookies",
                    docId:
                      "single-sign-on/faq/chrome-blocking-third-party-cookies",
                    unlisted: false,
                  },
                  {
                    type: "link",
                    label: "Proof of Key for Code Exchange",
                    href: "/docs/single-sign-on/faq/proof-of-key-for-code-exchange",
                    docId: "single-sign-on/faq/proof-of-key-for-code-exchange",
                    unlisted: false,
                  },
                ],
                collapsed: true,
                collapsible: true,
              },
            ],
            collapsed: true,
            collapsible: true,
          },
        ],
        collapsed: true,
        collapsible: true,
      },
    ],
  };